### ISSUE TITLE
Crash when fishing on a boat

### ISSUE THREAD

**Issue by Splizard** [MinetestForFun/fishing#1]
```
2016-02-10 17:55:41: ERROR[Main]: ServerError: Lua: Runtime error from mod 'fishing' in callback luaentity_Rightclick(): ~/.minetest/mods/fishing/bobber_shark.lua:77: attempt to index a nil value
2016-02-10 17:55:41: ERROR[Main]: stack traceback:
2016-02-10 17:55:41: ERROR[Main]:   /home/quentin/.minetest/mods/fishing/bobber_shark.lua:77: in function <~/.minetest/mods/fishing/bobber_shark.lua:65>
```

**Comment by ghost** [comment]
I don't know why this error but added a check.

**Comment by BetterToAutomateTheWorld** [comment]
Please, can you apply it on our servers @crabman77 ? :)

**Comment by ghost** [comment]
@Ombridride  already updated https://github.com/MinetestForFun/server-minetestforfun/commit/1d5af0a22a5d195262d91d5b44550f276ee4bd92

**Comment by BetterToAutomateTheWorld** [comment]
On the classic server, but not on the Creative server

**Comment by ghost** [comment]
creative has not fishing

**Comment by BetterToAutomateTheWorld** [comment]
Damn... the CREATIVE server really needs a merge from CLASSIC...
Anyway thank you, i will create an issue on creative :)

**Comment by Lymkwi** [comment]
There is something disturbing about this error. If this happened with the latest version of the code prior to your fix, then it means that `self` was unknown at the time the mod crashed. That would mean your fix would also crash since you index `self` earlier to determine whether or not it has a field called `owner`.
This is only my interpretation but I think you should (for some strange reason) check whether the bobber still exists upon right-clicking.
